title: Dubai Real Estate Analytics
description: Professional real estate investment analysis and portfolio optimization in Dubai

url: "https://ashish161.github.io"

# Theme settings
theme: jekyll-theme-minimal
plugins:
  - jekyll-seo-tag
  - jekyll-remote-theme
  - jekyll-sitemap


# Theme customization
show_downloads: false
logo: /assets/images/logo.png

# Basic settings
author: Naveen Daga 
google_analytics: # Optional

# SEO settings

social:
  name: Naveen Daga
  links:
    - https://www.linkedin.com/in/navindaga/

email: naveen@unnati.ae
lang: en
# Keep adding relevant keywors to this list
keywords: Dubai, real estate, analytics, investment, portfolio optimization, property, advisory

# Collections
title: Unnati.ae
collections:
  sections:
    output: true
    sort_by: order
