title: Dubai Real Estate Analytics
description: Professional real estate investment analysis and portfolio optimization in Dubai

url: "https://ashish161.github.io"

# Theme settings
theme: jekyll-theme-minimal
plugins:
  - jekyll-seo-tag
  - jekyll-remote-theme
  - jekyll-sitemap


# Theme customization
show_downloads: false
logo: /assets/images/logo.png

# Basic settings
author: Your Name
google_analytics: # Optional

# SEO settings
twitter:
  username: yourhandle
  card: summary
social:
  name: Your Name
  links:
    - https://linkedin.com/in/yourprofile
    - https://twitter.com/yourhandle

# Collections
title: My One-Page Site
collections:
  sections:
    output: true
    sort_by: order
