title: Dubai Real Estate Analytics
description: Professional real estate investment analysis and portfolio optimization in Dubai
baseurl: "/naveen"
url: "https://ashish161.github.io"

# Build settings
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag

# Theme settings
logo: /assets/images/logo.png
show_downloads: false

# Basic settings
author: Your Name

# SEO settings
twitter:
  username: yourhandle
  card: summary
social:
  name: Your Name
  links:
    - https://linkedin.com/in/yourprofile
    - https://twitter.com/yourhandle

# Analytics
google_analytics: UA-XXXXXXXX-X

# Collections
collections:
  services:
    output: true
    permalink: /:collection/:name
  market_insights:
    output: true
    permalink: /insights/:year/:month/:day/:title 
