name: Jekyll site CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1.0'
        bundler-cache: false

    - name: Update RubyGems
      run: |
        gem update --system 3.3.22
        gem install bundler

    - name: Configure Bundler
      run: |
        bundle config set --local deployment 'true'
        bundle config set --local frozen 'false'

    - name: Install dependencies
      run: |
        rm -f Gemfile.lock
        bundle install --jobs 4 --retry 3

    - name: Build site
      run: bundle exec jekyll build
      env:
        JEKYLL_ENV: production

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_site
        publish_branch: gh-pages